# Generated by Django 5.2.9 on 2026-02-06 02:14

from django.db import migrations
from django.utils import timezone


def backfill_time_created(apps, schema_editor):
    Ticket = apps.get_model("gestionlivre", "Ticket")
    Ticket.objects.filter(time_created__isnull=True).update(time_created=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("gestionlivre", "0003_alter_ticket_time_created_alter_ticket_user"),
    ]

    operations = [
        migrations.RunPython(backfill_time_created, migrations.RunPython.noop),
    ]
